"""Extend crm.lead with KB voice agent fields and pull-based CRM sync.

The sync works by polling the KB service's /v1/crm/pending endpoint
(using the already-configured KB URL and API key from kb_connector),
creating crm.lead records via ORM, and acknowledging each via
POST /v1/crm/processed/{id}.

This approach requires NO Odoo credentials on the KB service side.
"""
import json
import logging

import requests
from markupsafe import escape

from odoo import api, fields, models, _
from odoo.exceptions import UserError

logger = logging.getLogger(__name__)

_PRIORITY_MAP = {"hot": "3", "warm": "2", "cold": "1"}

_DEFAULT_TIMEOUT = 15  # seconds


class CrmLeadKB(models.Model):
    _inherit = "crm.lead"

    kb_call_uuid = fields.Char("Call UUID", readonly=True, copy=False)
    kb_conversation_summary = fields.Text(
        "AI Conversation Summary",
        readonly=True,
        help="AI-generated summary of the phone conversation.",
    )
    kb_customer_intent = fields.Selection(
        [
            ("purchase", "Purchase"),
            ("support", "Support"),
            ("inquiry", "Inquiry"),
            ("complaint", "Complaint"),
            ("return", "Return"),
            ("other", "Other"),
        ],
        string="Customer Intent",
        readonly=True,
    )
    kb_ai_priority = fields.Selection(
        [
            ("hot", "Hot"),
            ("warm", "Warm"),
            ("cold", "Cold"),
        ],
        string="AI Priority",
        readonly=True,
    )
    kb_sentiment = fields.Selection(
        [
            ("positive", "Positive"),
            ("neutral", "Neutral"),
            ("negative", "Negative"),
        ],
        string="Sentiment",
        readonly=True,
    )
    kb_suggested_action = fields.Char(
        "AI Suggested Action",
        readonly=True,
    )
    kb_transcript = fields.Text(
        "Call Transcript",
        readonly=True,
    )
    kb_recording_url = fields.Char(
        "Recording URL",
        readonly=True,
    )
    kb_ai_tags = fields.Char(
        "AI Tags",
        readonly=True,
        help="Comma-separated tags generated by AI analysis.",
    )
    kb_ai_confidence = fields.Float(
        "AI Confidence",
        readonly=True,
        digits=(3, 2),
    )

    # ── Pull-based CRM sync ─────────────────────────────────────

    @api.model
    def _cron_sync_from_kb(self):
        """Pull pending CRM leads from KB service and create them.

        Called by ir.cron every 5 minutes. Also available as a manual
        action from the CRM lead tree view.

        Uses the existing kb_connector settings (kb.service.url +
        kb.service.api_key) — no Odoo credentials needed on the KB side.
        """
        from odoo.addons.kb_connector.tools.kb_client import _get_config, _headers

        url, api_key = _get_config(self.env)

        try:
            resp = requests.get(
                f"{url}/v1/crm/pending",
                headers=_headers(api_key),
                timeout=_DEFAULT_TIMEOUT,
            )
            resp.raise_for_status()
        except requests.exceptions.ConnectionError:
            logger.warning("KB service unavailable at %s — skipping CRM sync", url)
            return
        except requests.exceptions.RequestException as exc:
            logger.error("CRM sync fetch failed: %s", exc)
            return

        pending = resp.json().get("calls", [])
        if not pending:
            return

        created = 0
        for call_data in pending:
            try:
                lead = self._import_call(call_data, url, api_key)
                if lead:
                    created += 1
            except Exception as exc:
                logger.error(
                    "Failed to import call %s: %s",
                    call_data.get("call_uuid", "?"),
                    exc,
                )

        if created:
            logger.info("KB CRM sync: created %d lead(s) from %d pending call(s)", created, len(pending))

    @api.model
    def _import_call(self, call_data, kb_url, api_key):
        """Import a single call record as a CRM lead. Returns the lead or None."""
        from odoo.addons.kb_connector.tools.kb_client import _headers

        call_uuid = call_data.get("call_uuid", "")

        # Idempotent — skip if already imported
        existing = self.search([("kb_call_uuid", "=", call_uuid)], limit=1)
        if existing:
            _mark_processed(kb_url, api_key, call_data["id"], existing.id)
            return None

        analysis = call_data.get("crm_analysis") or {}
        caller = call_data.get("caller_number", "Unknown")
        intent = analysis.get("customer_intent", "inquiry")
        intent_label = intent.replace("_", " ").title()

        lead = self.create({
            "name": f"[Voice] {intent_label} — {caller}",
            "type": "opportunity",
            "phone": caller,
            "description": _build_description(analysis, call_data),
            "priority": _PRIORITY_MAP.get(analysis.get("priority", "cold"), "1"),
            "kb_call_uuid": call_uuid,
            "kb_conversation_summary": analysis.get("summary", ""),
            "kb_customer_intent": intent if intent in dict(self._fields["kb_customer_intent"].selection) else "other",
            "kb_ai_priority": analysis.get("priority", "cold"),
            "kb_sentiment": analysis.get("sentiment", "neutral"),
            "kb_suggested_action": analysis.get("suggested_next_action", ""),
            "kb_transcript": json.dumps(call_data.get("transcript", []), indent=2),
            "kb_recording_url": call_data.get("recording_url", ""),
            "kb_ai_tags": ", ".join(analysis.get("tags", [])),
            "kb_ai_confidence": analysis.get("confidence", 0.0),
        })

        # Add transcript as chatter note
        transcript_html = _build_transcript_html(call_data.get("transcript", []))
        if transcript_html:
            lead.message_post(
                body=transcript_html,
                message_type="comment",
                subtype_xmlid="mail.mt_note",
            )

        # Acknowledge to KB service
        _mark_processed(kb_url, api_key, call_data["id"], lead.id)

        return lead

    def action_sync_from_kb(self):
        """Manual sync button action — pull pending leads from KB now."""
        self._cron_sync_from_kb()
        return {
            "type": "ir.actions.client",
            "tag": "display_notification",
            "params": {
                "title": _("KB Sync Complete"),
                "message": _("CRM leads synced from Knowledge Base service."),
                "type": "success",
                "sticky": False,
            },
        }


# ── Module-level helpers (pure functions) ────────────────────────


def _mark_processed(kb_url, api_key, call_id, lead_id):
    """Acknowledge a call as processed in the KB service."""
    from odoo.addons.kb_connector.tools.kb_client import _headers

    try:
        resp = requests.post(
            f"{kb_url}/v1/crm/processed/{call_id}",
            json={"lead_id": lead_id},
            headers=_headers(api_key),
            timeout=_DEFAULT_TIMEOUT,
        )
        resp.raise_for_status()
    except requests.exceptions.RequestException as exc:
        logger.warning("Failed to mark call %s as processed: %s", call_id, exc)


def _build_description(analysis, call_data):
    """Build HTML description for the CRM lead."""
    products = escape(", ".join(analysis.get("product_interest", [])) or "N/A")
    duration = int(call_data.get("duration_seconds", 0))
    confidence = float(analysis.get("confidence", 0))

    return (
        f"<b>AI Summary:</b> {escape(analysis.get('summary', 'N/A'))}<br/>"
        f"<b>Intent:</b> {escape(analysis.get('customer_intent', 'N/A'))}<br/>"
        f"<b>Products:</b> {products}<br/>"
        f"<b>Urgency:</b> {escape(analysis.get('urgency', 'N/A'))}<br/>"
        f"<b>Sentiment:</b> {escape(analysis.get('sentiment', 'N/A'))}<br/>"
        f"<b>Suggested Action:</b> {escape(analysis.get('suggested_next_action', 'N/A'))}<br/>"
        f"<b>AI Confidence:</b> {confidence:.0%}<br/>"
        f"<b>Call Duration:</b> {duration}s<br/>"
        f"<b>Call UUID:</b> {escape(call_data.get('call_uuid', 'N/A'))}"
    )


def _build_transcript_html(transcript):
    """Format transcript turns as HTML for Odoo chatter."""
    if not transcript:
        return ""

    lines = ["<h3>Call Transcript</h3>"]
    for turn in transcript:
        role = escape(turn.get("role", "unknown"))
        text = escape(turn.get("text", ""))
        confidence = turn.get("confidence")
        style = "color: #2196F3;" if str(role) == "bot" else "color: #333;"
        conf_str = f" ({float(confidence):.0%})" if confidence is not None else ""
        lines.append(
            f'<p style="{style}"><b>{role.upper()}</b>{conf_str}: {text}</p>'
        )
    return "".join(lines)
